baseURL = 'https://ShiroTatsuya.github.io/myblog/'
languageCode = 'zh-cn'
title = 'TRPG资料存档处'
theme = 'PaperMod'

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[params]
  buildFuture = true

[[menu.main]]
  name = '搜索'
  url = '/search/'
  weight = 1

[[menu.main]]
  name = '文章'
  url = '/posts/'
  weight = 2